[PREFERENCES]
# Values can be vertex, ollama or aistudio
mode = aistudio 
language = English
os = Linux
logging_level = WARNING

[MODEL]
# Only tool-calling models are supported
name = gemini-2.5-flash-preview-04-17
temperature = 0.0
max_retries = 2

[VERTEX]
project = <YOUR VERTEX PROJECT HERE>

[AISTUDIO]
google_api_key = <YOUR GOOGLE AI STUDIO API KEY HERE>