shortcut: debug
prompt: |
  Run the "{REPLACE}" command.
  Your task is to explain the *meaning and content* of the **actual standard output (stdout)** and **standard error (stderr)** produced by the command.
  If there is an error in the command output, explain how to fix it.